config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :migrants

  root "migrants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
  has_many :migrants
end

app/models/migrant.rb
class Migrant < ApplicationRecord
  belongs_to :state
  belongs_to :district
  belongs_to :panchayat
end

app/models/panchayat.rb
class Panchayat < ApplicationRecord
  has_many :migrants
end

app/models/state.rb
class State < ApplicationRecord
  has_many :migrants
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/migrants_controller.rb
class MigrantsController < ApplicationController
  before_action :set_migrant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create]

  # GET /migrants
  # GET /migrants.json
  def index
    @migrants = Migrant.all
  end

  # GET /migrants/1
  # GET /migrants/1.json
  def show
  end

  # GET /migrants/new
  def new
    @migrant = Migrant.new
  end

  # GET /migrants/1/edit
  def edit
  end

  # POST /migrants
  # POST /migrants.json
  def create
    @migrant = Migrant.new(migrant_params)

    respond_to do |format|
      if @migrant.save
        format.html { redirect_to @migrant, notice: 'Migrant was successfully created.' }
        format.json { render :show, status: :created, location: @migrant }
      else
        format.html { render :new }
        format.json { render json: @migrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /migrants/1
  # PATCH/PUT /migrants/1.json
  def update
    respond_to do |format|
      if @migrant.update(migrant_params)
        format.html { redirect_to @migrant, notice: 'Migrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @migrant }
      else
        format.html { render :edit }
        format.json { render json: @migrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /migrants/1
  # DELETE /migrants/1.json
  def destroy
    @migrant.destroy
    respond_to do |format|
      format.html { redirect_to migrants_url, notice: 'Migrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_migrant
      @migrant = Migrant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def migrant_params
      params.require(:migrant).permit(:name, :aadhar_id, :employer_name, :employer_phone,:local_residence, :state_id, :district_id, :panchayat_id, :can_speak_local_language, :has_labour_department_reached, :has_beds, :has_mattresses, :has_toilet, :has_general_cleanliness, :number_people_sharing_room, :has_cooking_facilities, :need_food, :need_water, :need_medicines, :need_doctor, :feedback_comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/migrants_helper.rb
module MigrantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Migrant Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-gray-100 leading-normal tracking-normal font-sans text-gray-900">
    <% if flash.alert %>
    <div class="bg-red-500 <%= 'hidden' if not flash.alert %>">
        <div class="container px-2 mx-auto py-2 py-4 text-white text-center"><%= flash[:alert] %></div>
    </div>
    <% else %>
    <div class="bg-green-500 <%= 'hidden' if not flash.notice %>">
        <div class="container px-2 mx-auto py-4 text-white text-center "><%= flash.notice %></div>
    </div>
    <% end %>
    <main class="p-4 lg:p-16 py-10 max-w-7xl mx-auto">
        <%= yield %>
    </main>
</body>

</html>

app/views/migrants/_form.html.erb
<section class="max-w-xl">
    <%= simple_form_for @migrant, defaults: { input_html: {class: 'form-input mt-1 font-sans'}, wrapper_html: {class: 'flex flex-col my-4'}, label_html: {class: 'mb-1'}} do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="pt-2">
        <%= f.input :name %>
        <%= f.input :aadhar_id %>
        <%= f.input :employer_name %>
        <%= f.input :employer_phone %>
    </div>

    <div class="pt-4">
        <%= f.input :local_residence %>
        <%= f.association :state, collection: State.all(), input_html: {class: 'form-select'} %>
        <%= f.association :district, collection: State.all(), input_html: {class: 'form-select'} %>
        <%= f.association :panchayat, collection: State.all(), input_html: {class: 'form-select'} %>
    </div>

    <div class="pt-4">
        <%= f.input :has_beds, input_html: {class: 'form-checkbox'} %>
        <%= f.input :has_mattresses, input_html: {class: 'form-checkbox'} %>
        <%= f.input :has_toilet, input_html: {class: 'form-checkbox'} %>
        <%= f.input :has_general_cleanliness, input_html: {class: 'form-checkbox'} %>
        <%= f.input :has_cooking_facilities, input_html: {class: 'form-checkbox'} %>
        <%= f.input :number_people_sharing_room %>
    </div>

    <div class="pt-4">
        <%= f.input :need_food, input_html: {class: 'form-checkbox'} %>
        <%= f.input :need_water, input_html: {class: 'form-checkbox'} %>
        <%= f.input :need_medicines, input_html: {class: 'form-checkbox'} %>
        <%= f.input :need_doctor, input_html: {class: 'form-checkbox'} %>
    </div>

    <div class="pt-2">
        <%= f.input :can_speak_local_language, input_html: {class: 'form-checkbox'} %>
        <%= f.input :has_labour_department_reached, input_html: {class: 'form-checkbox'} %>
        <%= f.input :feedback_comment %>
    </div>

    <div class="pt-4">
        <%= f.button :submit, "Register",class: 'p-2 rounded-md bg-gray-900 text-white shadow-md'  %>
    </div>
    <% end %>

</section>

app/views/migrants/edit.html.erb
<h1>Editing Migrant</h1>

<%= render 'form', migrant: @migrant %>

<%= link_to 'Show', @migrant %> |
<%= link_to 'Back', migrants_path %>

app/views/migrants/index.html.erb
<h1 class="text-xl font-bold">Migrants</h1>

<section class="pt-8">
    <table class="text-left border border-gray-700 w-full border-collapse">
        <thead class="border-b-2 border-gray-500">
            <tr>
                <th class="p-2">Name</th>
                <th class="p-2">Employer name</th>
                <th class="p-2">Local residence</th>
            </tr>
        </thead>

        <tbody>
            <% @migrants.each do |migrant| %>
            <tr class="border-t-2 border-gray-400">
                <td class="px-2"><%= migrant.name %></td>
                <td class="px-2"><%= migrant.employer_name %></td>
                <td class="px-2"><%= migrant.local_residence %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

    <br>
</section>

<div class="pt-4">
    <%= link_to 'Register Migrant', new_migrant_path, class: 'bg-gray-900 text-white p-2 rounded shadow-md' %>
</div>

app/views/migrants/new.html.erb
<h1 class="text-xl font-bold">Register as Migrant</h1>

<section class="pt-4">
    <%= render 'form', migrant: @migrant %>
</section>

<div class="pt-8">
    <%= link_to 'Back', migrants_path %>
</div>

app/views/migrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @migrant.name %>
</p>

<p>
  <strong>Employer name:</strong>
  <%= @migrant.employer_name %>
</p>

<p>
  <strong>Local residence:</strong>
  <%= @migrant.local_residence %>
</p>

<%= link_to 'Edit', edit_migrant_path(@migrant) %> |
<%= link_to 'Back', migrants_path %>